version: '>= 0.14.0'

formatter: markdown table

content: |-
  [![Tests](https://github.com/terraform-cisco-modules/terraform-intersight-policies-adapter-configuration/actions/workflows/test.yml/badge.svg)](https://github.com/terraform-cisco-modules/terraform-intersight-policies-adapter-configuration/actions/workflows/test.yml)
  # Terraform Intersight Policies - Adapter Configuration
  Manages Intersight Adapter Configuration Policies
  
  Location in GUI:
  `Policies` » `Create Policy` » `Adapter Configuration`

  ## Example

  ### main.tf
  ```hcl
  {{ include "examples/complete/main.tf" }}
  ```

  ### variables.tf
  ```hcl
  {{ include "examples/complete/variables.tf" }}
  ```

  ### versions.tf
  ```hcl
  {{ include "examples/complete/versions.tf" }}
  ```

  ## Environment Variables

  ### Terraform Cloud/Enterprise - Workspace Variables
  - Add variable apikey with value of [your-api-key]
  - Add variable secretkey with value of [your-secret-file-content]

  ### Linux
  ```bash
  export TF_VAR_apikey="<your-api-key>"
  export TF_VAR_secretkey=`cat <secret-key-file-location>`
  ```

  ### Windows
  ```bash
  $env:TF_VAR_apikey="<your-api-key>"
  $env:TF_VAR_secretkey="<secret-key-file-location>""
  ```


output:
  file: README.md
  mode: replace

sort:
  enabled: false